#!/bin/bash

for x in 50 100 150 200 250 300 350 400 450 500; do
cat > test.ini << EOF
&inputs
 Ngrid = ${x} 
 rho_max = 5.0
 Nsort = ${x}
 Nbody = 1
 omega_r = 5.0
 cyclic = .FALSE. 
 tol = 1.d-9
 nmax = 1000000
/
EOF
../../solver.x test.ini > grid${x}_classic.out 
gprof ../../solver.x > grid${x}-classic.profile
rm -f gmon.out  
rm -f test.ini

cat > test.ini << EOF
&inputs
 Ngrid = ${x}
 rho_max = 5.0
 Nsort = ${x} 
 Nbody = 1
 omega_r = 5.0
 cyclic = .TRUE. 
 tol = 1.d-9
 nmax = 1000000
/
EOF
../../solver.x test.ini > grid${x}_cyclic.out 
gprof ../../solver.x > grid${x}-cyclic.profile
rm -f gmon.out  
rm -f test.ini

done
